# Generated by Django 4.1.7 on 2023-03-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='state',
            field=models.CharField(blank=True, choices=[('unread', 'unread'), ('read', 'read')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='notif',
            name='action',
            field=models.CharField(blank=True, choices=[('cancel-request', 'cancel-request'), ('new-reservation', 'new-reservation'), ('cancel-approve', 'cancel-approve'), ('request-approve', 'request-approve')], max_length=15, null=True),
        ),
    ]
