# Generated by Django 4.1.7 on 2023-04-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notif_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notif',
            name='state',
            field=models.CharField(blank=True, choices=[('unread', 'unread'), ('read', 'read')], default='unread', max_length=6, null=True),
        ),
    ]
