# Generated by Django 4.1.7 on 2023-04-19 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notif_timestamp_alter_notif_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
