# Generated by Django 4.1.7 on 2023-04-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notif_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
