# Generated by Django 4.1.7 on 2023-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_last_reply_remove_comment_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(blank=True, choices=[('comment', 'comment'), ('user-reply', 'user-reply'), ('host-reply', 'host-reply')], default='comment', max_length=10, null=True),
        ),
    ]
