# Generated by Django 4.1.7 on 2023-03-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('denied', 'denied'), ('cancelled', 'cancelled'), ('current', 'current'), ('completed', 'completed'), ('terminated', 'terminated')], default='pending', max_length=10),
        ),
    ]
