# Generated by Django 4.1.7 on 2023-03-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('denied', 'denied'), ('cancel-pending', 'cancel-pending'), ('current', 'current'), ('completed', 'completed'), ('terminated', 'terminated'), ('approved', 'approved'), ('cancelled', 'cancelled')], default='pending', max_length=14),
        ),
    ]
