# Generated by Django 4.1.7 on 2023-03-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_restifyuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restifyuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='restifyuser',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
