# Generated by Django 4.1.7 on 2023-04-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_restifyuser_profile_pic_alter_restifyuser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restifyuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
