# Generated by Django 4.1.7 on 2023-03-18 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
